### ISSUE TITLE
Infercnv subcluster nomenclature

### ISSUE THREAD

**Issue by iheartfoosball** [harbourlab/uphyloplot2#10]
Hi team,

Thanks for the great package!

I am attempting to generate phylogenetic trees with subclustering info from infercnv, but it looks like my .cell_groupings file has a different subcluster nomenclature. When I run infercnv with the same sample data and code that's described in the Uphyloplot2 tutorial, the subcluster names in the .cell_groupings file are "all_observations.all_observations_s1" and so on. I am not seeing any groups labeled with the "all_observations.all_observations.1.1.1.1" format. Same pattern when I use my own data. Any idea why this might be?

Also I was thinking of trying to use the dendrogram file instead of the groupings, but I am not seeing the "newick_input.py" file anywhere in the Uphyloplot2 directory. Does this need to be ddownloaded from elsewhere?

Thank you!

Best,
Kaleab

**Comment by iheartfoosball** [comment]
Actually looks like the random trees method produces cluster names like 1.1.1, so maybe it's just dependent on method. Still curious about the newick script though.

**Comment by harbourlab** [comment]
Hi! I will upload the newick python script in a couple minutes, seemed to have been lost.

**Comment by iheartfoosball** [comment]
Thanks!
