### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 178: invalid start byte 

### ISSUE THREAD

**Issue by marlaherr** [harbourlab/uphyloplot2#11]
Hi there,
Thanks for sharing this tool! I am getting this error when trying to apply it to my inferCNV output:

```
(upuphyloplot2) -bash-4.2$ python uphyloplot2.py -I /icgc/dkfzlsdf/analysis/OE0519_projects/chptumor/marla/CNVproject/infer_CNV/Uphyloplot2/Inputs
UPhyloplot2 version 2.2
Traceback (most recent call last):
  File "/home/m221r/.conda/envs/upuphyloplot2/lib/python3.8/site-packages/uphyloplot2/uphyloplot2.py", line 239, in <module>
    main()
  File "/home/m221r/.conda/envs/upuphyloplot2/lib/python3.8/site-packages/uphyloplot2/uphyloplot2.py", line 35, in main
    for x, line in enumerate(groupings_file):
  File "/home/m221r/.conda/envs/upuphyloplot2/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 178: invalid start byte
```

I installed uphyloplot2 in a condo virtual environment using:
a) conda install -c amcruz uphyloplot2 --> from:https://anaconda.org/amcruz/uphyloplot2 (version2.2)
b) pip install git+https://github.com/harbourlab/uphyloplot2.git#egg=uphyloplot2 (version 2.3)

After installation of a) I could allocate an uphyloplot2.py file in the following directory: /home/user/.conda/envs/upuphyloplot2/lib/python3.8/site-packages/uphyloplot2
But running the python uphyloplot2.py command gave me the above error.

After installation of b) I could not find the uphyloplot2.py file at all.

Do you know what is causing this error and why I cannot find the uphyloplot2.py file in the 2.3 installation?
Any help would be highly appreciated. Thanks

Best

**Comment by harbourlab** [comment]
Hi, Could you please try and download the script as is? I think there is a problem with the conda and pip installation. Please let me know! Thanks!

**Comment by marlaherr** [comment]
Hi,
Thank you for your quick response. I found the source of the error. I had saved my input file in a different format after I removed the control samples in R. When using the proposed code for terminal it worked fine. Thanks anyways.

**Comment by harbourlab** [comment]
Perfect Thanks!
