### ISSUE TITLE
Using Uphyloplot2 with CaSpER data

### ISSUE THREAD

**Issue by bianchiniriccardo95** [harbourlab/uphyloplot2#13]
Hello!
First of all thank you for making this wonderful and useful tool. I am currently working with CaSpER, and I was wondering how I should process the CaSpER final object (the one obtained after running the runCaSpER function) in order to obtain a file suitable for the Uphyloplot2 Python algorithm.
Thanks in advance.

**Comment by harbourlab** [comment]
Hi! Try to generate a newick formatted tree. Uphyloplot 2 will read it.

**Comment by bianchiniriccardo95** [comment]
Thank you very much!
