### ISSUE TITLE
Phylograms look the same

### ISSUE THREAD

**Issue by MaximilianMerz** [harbourlab/uphyloplot2#2]
Hi there,

thank you for creating this awesome script. Unfortunately, I ran into some problems with creating the trees. I have 10x data from 10 different patients and performed the downstream analyses with Seurat.

When I run infer CNV, I get the heatmaps that are very consistent with FISH data and CNVs called from WES. When I use UPhyloplot2, all trees look the same, although there are clear differences between the samples.

Might it be a problem that I downsampled to 100 cells? Raw data from each sample contains more than 10,000 cells.

I ran inferCNV with HMM and analysis_mode = "subclusters" and a logistic noise filter.

Thanks in advance

Max

**Comment by harbourlab** [comment]
Hi sorry I just saw this. Are you still having issues?
