### ISSUE TITLE
I can"t find the HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.cell_groupings outcome

### ISSUE THREAD

**Issue by hzongyao** [harbourlab/uphyloplot2#3]
I can"t find the HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.cell_groupings outcome from InferCNV outcome,I wonder if I use the wrong parameter in InferCNV step，The code for the  InferCNV step as follows：

infercnv_obj <- infercnv::CreateInfercnvObject(raw_counts_matrix=exprMatrix, 
                                               gene_order_file=mm_geneLocate,
                                               annotations_file=cellAnnota,
                                               ref_group_names=c("control"))
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir='inferCNV/positive_1', 
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             HMM=TRUE,
                             num_threads=30)

> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] infercnv_1.2.1

**Comment by newbieMars** [comment]
Hi @hzongyao ,

You have to add ```analysis_mode="subclusters"``` in your infercnv::run() to generate the .cell_groupings file.

Best,

**Comment by hzongyao** [comment]
Could you proviede standard infercnv::run step code for me to study,Thank you!

**Comment by ccruizm** [comment]
Good day!
 I also ran `infercnv` with `analysis_mode="subclusters"` but cannot find the any `. cell_groupings` file in the output directory. The file ` HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_genes.dat 
` is there but not the one you refer in the instructions. The code I used for `infercnv` was:
```
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,  
                             out_dir="output",  
                             cluster_by_groups=F,  
                             analysis_mode="subclusters",
                             denoise=T,
                             HMM=T,
                             num_threads = 12
                             )
```

ANy ideas what can be the reason for this? thanks in advance!

**Comment by harbourlab** [comment]
Hi! Are you still having issues?

**Comment by raph06** [comment]
Hi there,
You can generate them..

###### Import your infercnv object
`infercnv_obj=readRDS('./infercnv_subclust_tumor/run.final.infercnv_obj')
`
###### parse the object and make a data.frame out of it
```
c_grp=t(as.data.frame(strsplit(names(unlist(infercnv_obj@tumor_subclusters$subcluster)),'[.](?=X)',perl = T)))
#use appropriate pattern matching
rownames(c_grp)=c(1:nrow(c_grp))
colnames(c_grp)=c("cell_group_name",	"cell")
c_grp=data.frame(c_grp)

```
###### write one file per samples (here according to value in hashing$ID
```
#rename cells if necessary
hashing=RenameCells(hashing,new.names = colnames(infercnv_obj@expr.data))

for (i in unique(hashing$ID))
{
  n=grep(i,c_grp$cell_group_name)
  write.table(c_grp[n,],paste('./infercnv_subclust_tumor/Inputs/',i,'.cell_groupings',sep=''),col.names = T,row.names = F,quote = F)
  
}
```

Best,
R
