### ISSUE TITLE
Error running with cluster_by_groups set to FALSE

### ISSUE THREAD

**Issue by s849** [harbourlab/uphyloplot2#4]
Hi,

Thanks for this awesome tool. I encounter the following error when I set cluster_by_groups set to FALSE:

Error in if (runif(1) <= padj) { : missing value where TRUE/FALSE needed

This is my infercnv code:
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir='output', 
                             cluster_by_groups=FALSE, 
                             denoise=TRUE,
                             HMM=TRUE)

Any ideas why this might be the case? 

Thank you!

**Comment by harbourlab** [comment]
I would recommend getting in touch with the authors of infercnv. I have not much expertise in running it myself actually...
