### ISSUE TITLE
Figure 2 of your Nat Common paper

### ISSUE THREAD

**Issue by s849** [harbourlab/uphyloplot2#5]
Hello,

Thank you for providing this very useful tool. I am wondering how/where can I find information about q and p to generate a heatmap similar to figure 2b in your paper, and also add the information about LOH rain the clonality trees?

Thank you!

**Comment by harbourlab** [comment]
Hi! We did this manually by looking at the inferCNV output files. Unfortunately that is not automated.

**Comment by s849** [comment]
Thanks for your response!

Sorry but I have one more question - who output files should I look at?

Also, how did you guys generate the p/q arm data and from what output file?

Thanks for your help!

**Comment by harbourlab** [comment]
There should be an output file from infer CNV that gives you all the gains and losses called. It's manual labour from there ;) the p and q arm information you can infer from the positions of the gains and losses, you'll just have to look up where p and q arms start/end. Hope that helps!

**Comment by angkoomin** [comment]
Hi there, 

Do you mind elaborating which files you used for annotating each branch?  

I got these files, however, I'm not too sure how do you categorise the loss/gain seen to the truncal/higher branches as all the results are seen in my end branches/leaves of the phylo tree

Thanks

![image](https://user-images.githubusercontent.com/61758903/162091130-1f20389c-3559-4562-ae7f-b7c6b6424eba.png)

**Comment by harbourlab** [comment]
Hi!

Unfortunately that is nothing UPhyloplot does automatically at the moment. It needs some manual curation from the user.

UPhyloplot2 will not identify the characteristic CNV changes for each subclone. If desired, these have to be be inferred manually for each subclone IDs in the "HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat file from the inferCNV output manually.

With this file, you will have to choose your own cutoffs and thresholds to call your desired gains and losses.

Hope this helps…

Stefan
________________________________________________________________
Stefan Kurtenbach, Ph.D.
Research Assistant Professor
Department of Ophthalmology, Bascom Palmer Eye Institute
University of Miami Miller School of Medicine
Sylvester Comprehensive Cancer Center
Director, ISCI Pluripotent Stem Cell Laboratory

Biomedical Research Building Room 913
1501 NW 10th Avenue, Miami, FL 33136
305-243-3892 office, 786-252-4379 cell
***@***.******@***.***>

On Apr 6, 2022, at 7:37 PM, angkoomin ***@***.******@***.***>> wrote:

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.



Hi there,

Do you mind elaborating which files you used for annotating each branch?

I got these files, however, I'm not too sure how do you categorise the loss/gain seen to the truncal/higher branches as all the results are seen in my end branches/leaves of the phylo tree

Thanks

[image]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F61758903%2F162091130-1f20389c-3559-4562-ae7f-b7c6b6424eba.png&data=04%7C01%7CStefan.Kurtenbach%40med.miami.edu%7C58a1e5c6bd3b460ad7f508da18265c62%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637848850284227790%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DVRVotr%2F7wv5znK%2BW8QOgPbV%2F2M9vLkFaYYmUtakipQ%3D&reserved=0>

**Comment by angkoomin** [comment]
Thanks for your comments. For example in the screenshot from the post above, for subclone 'D', it is represented by '1.1.1.1'. Does that mean that 26% (based on the left bottom figure) of my cells have the chromosomal gain/loss represented by all the '1.1.1.1' rows?

Secondly, what about the upper branches (i.e. B, C), how do I get information about the gains/losses for prior to each bifurcation? Example in this figure below:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/61758903/162226830-c525db4d-5668-4153-b38d-4f06505cb4b2.png">
From: Durante, M.A., Rodriguez, D.A., Kurtenbach, S. et al. Single-cell analysis reveals new evolutionary complexity in uveal melanoma. Nat Commun 11, 496 (2020). https://doi.org/10.1038/s41467-019-14256-1

**Comment by angkoomin** [comment]
Hi Stefan,

I wondered if you could help explain how do I get to label each branch as the Durante paper with the "HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat" file. 

I can't seem to get my head around labelling the branches.

This is a wonderful tool, but I think I need help in naming the branches accordingly.

Thanks

**Comment by harbourlab** [comment]
Hi!

I did not do this myself for this paper, but it all boils down to manual labour really. Once you define gains and losses for your sub clones, using own thresholds and calls, you can go backwards and infer at which branch certain mutations have arisen to some extent, like gain and loss of a chromosome arm for instance. Let me know if that helps, else I can forward your questions to the other co-authors.. in which case please write me an email and I can forward.

Cheers
Stefan


________________________________________________________________
Stefan Kurtenbach, Ph.D.
Research Assistant Professor
Department of Ophthalmology, Bascom Palmer Eye Institute
University of Miami Miller School of Medicine
Sylvester Comprehensive Cancer Center
Director, ISCI Pluripotent Stem Cell Laboratory

Biomedical Research Building Room 913
1501 NW 10th Avenue, Miami, FL 33136
305-243-3892 office, 786-252-4379 cell
***@***.******@***.***>

On Apr 11, 2022, at 5:27 AM, angkoomin ***@***.******@***.***>> wrote:

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.



Hi Stefan,

I wondered if you could help explain how do I get to label each branch as the Durante paper with the "HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat" file.

I can't seem to get my head around labelling the branches.

This is a wonderful tool, but I think I need help in naming the branches accordingly.

Thanks

**Comment by angkoomin** [comment]
Hi Stefan,

Thanks for your answer. I have emailed you and hopefully, you can forward it to the authors. Once I have got the answer, I hope to share this with the community on how to go about this.

Thanks
